@startuml
|EntryDispatcher|
start
' 主节点向从节点发送推送请求的类型，在PushEntryRequest.Type中定义，
' 可选值如下:
'
' 1. COMPARE：如果Leader节点发生变化，新的Leader节点需要与
'    它的从节点日志条目进行比较，以便截断从节点多余的数据。
' 2. TRUNCATE：如果Leader节点通过索引完成日志对比后，发现从
'    节点存在多余的数据（未提交的数据），则Leader节点将发送
'    TRUNCATE给它的从节点，删除多余的数据，实现主从节点数据一
'    致性。
' 3. APPEND：将日志条目追加到从节点。
' 4. COMMIT：通常Leader节点会将提交的索引附加到append请求，如果
'    append请求很少且分散，Leader节点将发送一个单独的请求来
'    通知从节点提交索引。
partition doWork() {
    partition checkAndFreshState() {
        :if not leader, return;
        :if is new leader, change to COMPARE state;
    }
    if () 
}
end
@enduml