name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install and Build
        run: |
          npm ci
          npm run build
        working-directory: docs
      
      - name: vuepress-deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: HScarb/HScarb.github.io
          publish_branch: master
          publish_dir: docs/src/.vuepress/dist
